version: 2
jobs:
  build:
    docker:
      - image: jonakoudijs/hadolint:latest

    steps:
      - checkout
      - run:
          name: Run Hadolint test
          command: git ls-files --exclude='Dockerfile*' --ignored | xargs hadolint
